service: municourt
image: aosik/municourt

servers:
  web:
    - 89.167.56.225

proxy:
  ssl: true
  host: municourt.hackjc.org
  app_port: 8080

registry:
  username: aosik
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
